# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22ad13fd890af15f66ca3b4e69b0f7a3c593da02fc5f0dcedc0699124cc5dd67535c8d468ef58350be4a28107175e8af4d3f659d29b0adef8ced139df055d554

test:
  secret_key_base: f4c27c9e09d4ae58e1616548d1772e6648f5a7c4d05c9ec374288baa5395dcb788d652c3ec201478cb9323dc1f5a799f491417326f5d52646485ccda715fc68f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
